config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get '/logout' => 'sessions#destroy', as: :logout

  resources :users
  resources :sessions, only: [:new, :create]

  get 'arts' => 'arts#index'
  get 'users/:id/arts' => 'arts#user_arts', as: :user_arts
  resources :arts

end

app/models/art.rb
class Art < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  validates :avatar, presence: true

  has_attached_file :avatar, styles: { :medium => "250x200" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :art
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :arts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end #current_user

  def logged_in?
    !!current_user
  end # logged_in

  def authorize
    unless logged_in?
      redirect_to new_session_path
  end
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  def index
    @arts = Art.all
  end
  def user_arts
    @arts = current_user.arts
  end
  def new
    @art = Art.new
  end

  def edit
    @art = Art.find(params[:id])
  end

  def update
    @art = Art.find(params[:id])

    if @art.update(art_params)
      redirect_to user_arts_path, :notice => "Updated"
    else
      render "edit"
  end
end

  def show
  end

  def create
    @art = current_user.arts.new(art_params)
    if @art.save
      redirect_to user_arts_path(current_user.id)
    else
      redirect_to root_path
    end
  end

  def destroy
    @art = Art.find(params[:id]).destroy
    redirect_to user_arts_path(current_user.id)
  end

  private
  def art_params
    params.require(:art).permit(:title, :description, :avatar, :image_url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to user_arts_path(@user.id)
      else
        redirect_to new_session_path
  end
end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to user_arts_path(@user.id)
    else
      render :new
  end
end


  def edit
  end

  def show
    @user = User.find(params[:id])
  end

  def update
  end

  def destroy
  end
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/arts/edit.html.erb
<h2>Edit</h2>
<%= simple_form_for @art do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div>
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

<%= f.submit "Save Changes" %>

<% end %>

<%= link_to "Back 2 Your Art", user_arts_path %>

app/views/arts/index.html.erb
<h1>Art</h1>
<div style="display: inline">
  <%= link_to "Upload", new_art_path %>
</div>
<% @arts.each do |a| %>
<div style="display: inline-block;">
  <h3> <%= a.title %></h3>
  <%= image_tag a.avatar.url(:medium) %>


  <p><%= a.description %></p>

</div>
<% end %>

app/views/arts/new.html.erb
<h1>Arts#new</h1>
<p>Find me in app/views/arts/new.html.erb</p>
<%= simple_form_for @art do |f| %>
  <%= f.input :avatar %>
  <%= f.button :submit %>
  <% end %>

app/views/arts/show.html.erb
<h1>Arts#show</h1>
<p>Find me in app/views/arts/show.html.erb</p>

app/views/arts/user_arts.html.erb
<h1 style="font-family: 'Desdemona'; font-size: 46px; font-style: italic; color: rgba(59, 255, 0, 0.46);">Art</h1>
<div style="display: inline">
  <h3 style="font-family: 'Lobster Two', cursive; font-style: italic; color: rgba(255, 255, 255, 0.84);"><%= link_to "Upload", new_art_path %></h3>

</div>
<% @arts.each do |a| %>
<div style="display: inline-block;">
  <h3 style="color: rgb(255, 168, 0);"> <%= a.title %></h3>
  <%= link_to "Edit", edit_art_path(a) %>
  <%= image_tag a.avatar.url(:medium) %>
  <br>
  <%= link_to "Delete", art_path(a), method: :delete, data: {confirm: "Are you fucking kidding me?"} %>

  <p style="color: rgb(32, 255, 177); margin-top: 10px; margin-bottom: 0px;"><%= a.description %></p>

</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WearsArtist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lobster+Two:400italic' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <%= favicon_link_tag 'favicon.png' %>
</head>
<body>
<%= render partial: "shared/navbar" %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="" style="font-family: 'Lobster Two', cursive; font-style: italic; color: rgba(255, 161, 0, 0.84);" >wearsArtist</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Sign Up", new_user_path %></li>
            <li><a href="#"><%= link_to "Upload", new_art_path %></a></li>
            <li><a href="#">Mark Down</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Logout", logout_path %></li>
          <li><%= link_to "Profile", user_arts_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Login", new_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1 style="font-family: Desdemona; font-size: 46px; color: rgb(255, 184, 0);">wearsArtist</h1>

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-yw4l{vertical-align:top}
</style>
<table class="tg">
  <tr>
    <td class="tg-031e"><img src="http://fabrik.la/wp-content/uploads/2013/01/The-LA-Art-Show-02.jpg" style="width: 300px; height: 250px;"></td>
    <td class="tg-yw4l"><img src="http://www.ucira.ucsb.edu/wp-content/files_flutter/1350331757la-et-cm-street-art-bonhams-auction-20121010-001.jpeg" style="width: 300px; height: 250px;"></td>
    <td class="tg-yw4l"><img src="http://www.brooklynstreetart.com/theblog/wp-content/uploads/2011/05/brooklyn-street-art-dface-jaime-rojo-corey-helford-gallery-los-angeles-04-11-2-web.jpg" style="width: 300px; height: 250px;"></td>
  </tr>
  <tr>
    <td class="tg-yw4l"><img src="http://lastreetartgallery.com/wp-content/uploads/2015/04/thamer.jpg" style="width: 300px; height: 250px;"></td>
    <td class="tg-yw4l"><img src="http://iyftc1oqf704bytwz45ub151.wpengine.netdna-cdn.com/wp-content/uploads/2013/06/KOBRA-RUSHMORE.jpg" style="width: 300px; height: 250px;"></td>
    <td class="tg-yw4l"><img src="http://wanderingtrader.com/wp-content/uploads/2013/04/la-robot-de-madera-y-charquipunk-valparaiso-1000x618.jpg" style="width: 300px; height: 250px;"></td>
  </tr>
  <tr>
    <td class="tg-yw4l"><img src="http://www.fubiz.net/wp-content/uploads/2015/10/sagmeister-3-900x585.jpg" style="width: 300px; height: 250px;"></td>
    <td class="tg-yw4l"><img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSCaaXO3AV0kTrOmecHi1_JUp-lEP3yRCDHpbBllmJA_RmP_-jE0A" style="width: 300px; height: 250px;"></td>
    <td class="tg-yw4l"><img src="http://groupon.s3.amazonaws.com/sponsorship-imgs/Goods/Celebrity%20Canvas%20Prints/638211900019_Celebrity_Canvas_Print__Jimi_Hendrix_Paint.jpg" style="width: 300px; height: 250px;"></td>
  </tr>
</table>

app/views/users/new.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :name, label: 'Your username please', error: 'Username is mandatory, please specify one' %>
  <%= f.input :password, hint: 'No special characters.' %>
  <%= f.input :email, placeholder: 'user@domain.com' %>
  <%= f.button :submit %>
<% end %>

app/views/users/show.html.erb
<h1>profile</h1>
<%= @art.user.email %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>